import type { AssetInput } from '@pascal-app/core'

export const CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'threadmill',
    category: 'furniture',
    name: 'Threadmill',
    tags: ['floor', 'fitness'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/threadmill/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/threadmill/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/threadmill/floor-plan.png',
    dimensions: [2.5, 1.5, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'herman-miller-aeron-mo8x36k9',
    category: 'furniture',
    name: 'Herman Miller Aeron',
    tags: ['office'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/herman-miller-aeron-mo8x36k9/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/herman-miller-aeron-mo8x36k9/models/item_model_YshL4maC8cHtry5c.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/herman-miller-aeron-mo8x36k9/floor-plan.png',
    dimensions: [1, 1.0507, 1],
    offset: [-0.0013, 0.5256, 0.0028],
    rotation: [0, 0, 0],
    scale: [1.05, 1.05, 1.05],
  },
  {
    id: 'tv-stand',
    category: 'furniture',
    name: 'TV Stand',
    tags: ['floor', 'storage'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tv-stand/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tv-stand/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tv-stand/floor-plan.png',
    dimensions: [2, 0.4, 0.5],
    offset: [0, 0.21, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.36 },
  },
  {
    id: 'standing-desk-mo8wgz95',
    category: 'furniture',
    name: 'Standing Desk',
    tags: ['office'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/standing-desk-mo8wgz95/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/standing-desk-mo8wgz95/models/item_model_zzZ58018waP8VY6Z.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/standing-desk-mo8wgz95/floor-plan.png',
    dimensions: [1.5, 0.8433, 1],
    offset: [0.0001, 0.4203, 0.0019],
    rotation: [0, 0, 0],
    scale: [1.4, 1.4, 1.4],
  },
  {
    id: 'dining-table-mo9ms5yh',
    category: 'furniture',
    name: 'Dining table',
    tags: ['dining', 'table', 'dinette', 'wood', 'oak', 'modern', 'minimalist', 'scandinavian', 'rectangular', 'kitchen', 'mealtime', 'entertaining'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table-mo9ms5yh/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table-mo9ms5yh/models/item_model_Sffq4hIGw8R3keLh.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table-mo9ms5yh/floor-plan.png',
    dimensions: [2, 0.7641, 1],
    offset: [0.0002, 0.3793, -0.0026],
    rotation: [0, 0, 0],
    scale: [2, 2, 2],
    surface: { height: 0.77 },
  },
  {
    id: 'cactus',
    category: 'furniture',
    name: 'Cactus',
    tags: ['cactus', 'rack', 'stand', 'hanger', 'sculpture', 'decor', 'modern', 'contemporary', 'pop', 'green', 'organizer', 'storage', 'sculptural'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cactus/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cactus/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cactus/floor-plan.png',
    dimensions: [0.5, 0.4, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'piano',
    category: 'furniture',
    name: 'Piano',
    tags: ['piano', 'instrument', 'musical', 'grand', 'upright', 'keyboard', 'wood', 'polished', 'lacquer', 'ebony', 'classic', 'traditional', 'music', 'entertainment', 'luxury'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/piano/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/piano/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/piano/floor-plan.png',
    dimensions: [2, 1.5, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'car-toy',
    category: 'furniture',
    name: 'Car Toy',
    tags: ['car', 'toy', 'vehicle', 'racer', 'play', 'nursery', 'playroom', 'wooden', 'vintage', 'decor', 'kids', 'child', 'classic', 'miniature', 'hobby'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/car-toy/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/car-toy/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/car-toy/floor-plan.png',
    dimensions: [0.5, 0.4, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'single-bed',
    category: 'furniture',
    name: 'Single Bed',
    tags: ['floor', 'bedroom'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/single-bed/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/single-bed/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/single-bed/floor-plan.png',
    dimensions: [1.5, 0.7, 2.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ikea-kallax-1x4-moa2y49n',
    category: 'furniture',
    name: 'Ikea Kallax 2x4',
    tags: ['shelf', 'bookcase', 'shelving', 'storage', 'organizer', 'cubby', 'cube', 'scandinavian', 'modern', 'minimalist', 'wood', 'laminate', 'display', 'modular'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ikea-kallax-1x4-moa2y49n/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ikea-kallax-1x4-moa2y49n/models/item_model_ocVHS1SWDex5DeYc.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ikea-kallax-1x4-moa2y49n/floor-plan.png',
    dimensions: [1.5, 2.059, 1],
    offset: [0, -0.0053, 0],
    rotation: [0, 0, 0],
    scale: [1.4, 1.4, 1.4],
  },
  {
    id: 'livingroom-chair',
    category: 'furniture',
    name: 'Livingroom Chair',
    tags: ['chair', 'armchair', 'seating', 'lounge', 'upholstered', 'modern', 'fabric', 'furniture', 'minimalist', 'comfort', 'accent', 'lounger'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/livingroom-chair/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/livingroom-chair/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/livingroom-chair/floor-plan.png',
    dimensions: [1.5, 0.8, 1.5],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'small-indoor-plant',
    category: 'furniture',
    name: 'Small Plant',
    tags: ['countertop', 'decor', 'vegetation'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/small-indoor-plant/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/small-indoor-plant/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/small-indoor-plant/floor-plan.png',
    dimensions: [0.5, 0.7, 0.5],
    offset: [-0.01, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bookshelf',
    category: 'furniture',
    name: 'Bookshelf',
    tags: ['bookshelf', 'bookcase', 'shelving', 'storage', 'organizer', 'modern', 'minimalist', 'wood', 'metal', 'industrial', 'library', 'office', 'furniture', 'display', 'timber'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bookshelf/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bookshelf/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bookshelf/floor-plan.png',
    dimensions: [1, 2, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'closet',
    category: 'furniture',
    name: 'Closet',
    tags: ['closet', 'wardrobe', 'armoire', 'cabinet', 'storage', 'organization', 'wood', 'bedroom', 'modern', 'minimalist', 'clothing', 'apparel', 'cupboard', 'locker'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/closet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/closet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/closet/floor-plan.png',
    dimensions: [2, 2.5, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'column',
    category: 'furniture',
    name: 'Column',
    tags: ['column', 'pillar', 'pedestal', 'plinth', 'stand', 'marble', 'stone', 'classical', 'roman', 'greek', 'decorative', 'architectural', 'antique', 'support', 'base'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/column/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/column/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/column/floor-plan.png',
    dimensions: [0.5, 2.6, 0.5],
    offset: [0, 1.26, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'picture',
    category: 'furniture',
    name: 'Picture',
    tags: ['picture', 'frame', 'art', 'artwork', 'print', 'canvas', 'decor', 'modern', 'abstract', 'minimalist', 'decorative', 'glass', 'wood', 'illustration', 'portrait'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/picture/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/picture/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/picture/floor-plan.png',
    dimensions: [2, 1, 0.2],
    offset: [0.02, 0.45, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'books',
    category: 'furniture',
    name: 'Books',
    tags: ['books', 'novels', 'literature', 'reading', 'vintage', 'classic', 'decorative', 'paper', 'leather', 'library', 'study', 'office', 'decor', 'shelf', 'antique'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/books/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/books/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/books/floor-plan.png',
    dimensions: [0.5, 0.3, 0.5],
    offset: [-0.08, 0, 0.02],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coat-rack',
    category: 'furniture',
    name: 'Coat Rack',
    tags: ['coatrack', 'rack', 'hanger', 'valet', 'organizer', 'storage', 'entryway', 'hallway', 'minimalist', 'metal', 'wood', 'mudroom', 'hooks', 'clothes'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coat-rack/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coat-rack/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coat-rack/floor-plan.png',
    dimensions: [0.5, 1.8, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'easel',
    category: 'furniture',
    name: 'Easel',
    tags: ['easel', 'stand', 'tripod', 'art', 'studio', 'wood', 'display', 'canvas', 'atelier', 'presentation', 'wooden', 'sketching', 'painting', 'decor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/easel/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/easel/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/easel/floor-plan.png',
    dimensions: [1.5, 2.3, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'floor-lamp',
    category: 'furniture',
    name: 'Floor Lamp',
    tags: ['lamp', 'luminaire', 'light', 'torchere', 'lighting', 'illumination', 'metal', 'brass', 'modern', 'minimalist', 'industrial', 'decor', 'ambient', 'reading', 'sleek'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/floor-lamp/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/floor-lamp/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/floor-lamp/floor-plan.png',
    dimensions: [1, 1.9, 1],
    offset: [0.04, 0, 0.02],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    interactive: {
      controls: [
        { kind: 'toggle' },
        { kind: 'slider', label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial', default: 100 },
      ],
      effects: [
        { kind: 'light', intensityRange: [0, 2], color: '#ffffff', offset: [0, 1.4, 0] },
      ],
    },
  },
  {
    id: 'rectangular-carpet',
    category: 'furniture',
    name: 'Rectangular Carpet',
    tags: ['carpet', 'rug', 'mat', 'textile', 'woven', 'rectangular', 'modern', 'wool', 'cotton', 'minimalist', 'decor', 'plush'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/rectangular-carpet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/rectangular-carpet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/rectangular-carpet/floor-plan.png',
    dimensions: [3, 0.1, 2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'indoor-plant',
    category: 'furniture',
    name: 'Indoor Plant',
    tags: ['plant', 'greenery', 'botanical', 'foliage', 'houseplant', 'organic', 'natural', 'modern', 'minimalist', 'tropical', 'decor', 'accent', 'green', 'ceramic'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/indoor-plant/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/indoor-plant/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/indoor-plant/floor-plan.png',
    dimensions: [1, 1.7, 1],
    offset: [-0.05, 0, 0.07],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stool',
    category: 'furniture',
    name: 'Stool',
    tags: ['floor', 'seating'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stool/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stool/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stool/floor-plan.png',
    dimensions: [1, 1.2, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell',
    category: 'furniture',
    name: 'Barbell',
    tags: ['barbell', 'weight', 'steel', 'iron', 'metal', 'gym', 'fitness', 'industrial', 'workout', 'strength', 'training', 'lifting', 'chrome', 'exercise'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell/floor-plan.png',
    dimensions: [0.5, 0.4, 2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'lounge-chair',
    category: 'furniture',
    name: 'Lounge Chair',
    tags: ['chair', 'armchair', 'seating', 'lounge', 'seat', 'modern', 'contemporary', 'minimalist', 'comfort', 'relaxation', 'upholstered', 'interior', 'furniture'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/lounge-chair/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/lounge-chair/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/lounge-chair/floor-plan.png',
    dimensions: [1, 1.1, 1.5],
    offset: [0, 0, 0.09],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pool-table',
    category: 'furniture',
    name: 'Pool table',
    tags: ['pool', 'billiards', 'snooker', 'table', 'recreation', 'leisure', 'entertainment', 'wood', 'felt', 'gaming', 'traditional', 'luxury', 'classic', 'hobby', 'furniture'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pool-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pool-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pool-table/floor-plan.png',
    dimensions: [2.5, 1, 4],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toy',
    category: 'furniture',
    name: 'Toy',
    tags: ['floor', 'kids', 'decor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toy/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toy/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toy/floor-plan.png',
    dimensions: [0.5, 0.5, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ironing-board',
    category: 'furniture',
    name: 'Ironing Board',
    tags: ['ironing', 'board', 'laundry', 'foldable', 'metal', 'utility', 'pressing', 'collapsible', 'stand', 'table', 'organization', 'industrial'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ironing-board/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ironing-board/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ironing-board/floor-plan.png',
    dimensions: [1.5, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'office-chair',
    category: 'furniture',
    name: 'Office Chair',
    tags: ['chair', 'seating', 'ergonomic', 'swivel', 'office', 'desk', 'mesh', 'leather', 'modern', 'task', 'workspace', 'professional', 'computer'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-chair/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-chair/model.glb',
    floorPlanUrl: '/items/office-chair/floor-plan.svg',
    dimensions: [1, 1.2, 1],
    offset: [0.01, 0, 0.03],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell-stand',
    category: 'furniture',
    name: 'Barbell Stand',
    tags: ['rack', 'stand', 'holder', 'storage', 'metal', 'steel', 'industrial', 'fitness', 'gym', 'weightlifting', 'training', 'minimalist', 'black', 'organizer'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell-stand/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell-stand/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/barbell-stand/floor-plan.png',
    dimensions: [1.5, 1.3, 2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bedside-table',
    category: 'furniture',
    name: 'Bedside Table',
    tags: ['nightstand', 'table', 'bedroom', 'storage', 'wood', 'modern', 'minimalist', 'stand', 'drawer', 'furniture', 'cabinet', 'bedside'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bedside-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bedside-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bedside-table/floor-plan.png',
    dimensions: [0.5, 0.5, 0.5],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.5 },
  },
  {
    id: 'coffee-table',
    category: 'furniture',
    name: 'Coffee Table',
    tags: ['table', 'cocktail', 'wood', 'modern', 'minimalist', 'furniture', 'living', 'lounge', 'walnut', 'metal', 'glass', 'surface', 'decor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coffee-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coffee-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/coffee-table/floor-plan.png',
    dimensions: [2, 0.4, 1.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.3 },
  },
  {
    id: 'sofa',
    category: 'furniture',
    name: 'Sofa',
    tags: ['floor', 'seating'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sofa/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sofa/model.glb',
    floorPlanUrl: '/items/sofa/floor-plan.svg',
    dimensions: [2.5, 0.8, 1.5],
    offset: [0, 0, 0.04],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'office-table',
    category: 'furniture',
    name: 'Office Table',
    tags: ['desk', 'table', 'workstation', 'furniture', 'office', 'work', 'study', 'writing', 'modern', 'minimalist', 'industrial', 'wood', 'metal'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/office-table/floor-plan.png',
    dimensions: [2, 0.8, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.75 },
  },
  {
    id: 'double-bed',
    category: 'furniture',
    name: 'Double Bed',
    tags: ['bed', 'bedstead', 'double', 'frame', 'bedroom', 'sleeping', 'modern', 'minimalist', 'upholstered', 'wood', 'sleep', 'furniture', 'contemporary'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/double-bed/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/double-bed/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/double-bed/floor-plan.png',
    dimensions: [2, 0.8, 2.5],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'my-leather-couch-modp80ha',
    category: 'furniture',
    name: 'My leather couch',
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/my-leather-couch-modp80ha/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/my-leather-couch-modp80ha/models/item_model_m08TPqPVP5cVNiIU.glb',
    dimensions: [1, 0.3323, 0.5],
    offset: [-0.0003, 0.1614, -0.002],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bunkbed',
    category: 'furniture',
    name: 'Bunkbed',
    tags: ['bunkbed', 'bed', 'sleeper', 'loft', 'bedroom', 'kids', 'wood', 'metal', 'modern', 'sleeping', 'ladder', 'rustic', 'dormitory', 'furniture'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bunkbed/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bunkbed/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bunkbed/floor-plan.png',
    dimensions: [2, 1.6, 1.5],
    offset: [0, 0, -0.09],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dining-table',
    category: 'furniture',
    name: 'Dining Table',
    tags: ['table', 'dining', 'furniture', 'wood', 'modern', 'minimalist', 'kitchen', 'eating', 'surface', 'contemporary', 'gathering', 'walnut'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-table/floor-plan.png',
    dimensions: [2.5, 0.8, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.8 },
  },
  {
    id: 'guitar',
    category: 'furniture',
    name: 'Guitar',
    tags: ['guitar', 'instrument', 'musical', 'wood', 'acoustic', 'vintage', 'classic', 'decor', 'mahogany', 'string', 'art', 'hobby'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/guitar/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/guitar/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/guitar/floor-plan.png',
    dimensions: [0.5, 1.2, 0.5],
    offset: [0, 0.32, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'trash-bin',
    category: 'furniture',
    name: 'Trash Bin',
    tags: ['floor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/trash-bin/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/trash-bin/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/trash-bin/floor-plan.png',
    dimensions: [0.5, 0.6, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'recessed-light',
    category: 'furniture',
    name: 'Recessed Light',
    tags: ['recessed', 'downlight', 'spotlight', 'lighting', 'fixture', 'modern', 'minimalist', 'metal', 'aluminum', 'luminaire', 'ambient', 'illumination', 'architectural', 'can'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/recessed-light/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/recessed-light/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/recessed-light/floor-plan.png',
    dimensions: [0.5, 0.1, 0.5],
    offset: [0, 0.094, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' },
        { kind: 'slider', label: 'Intensity', min: 0, max: 100, unit: '%', displayMode: 'dial', default: 100 },
      ],
      effects: [
        { kind: 'light', intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.1, 0] },
      ],
    },
  },
  {
    id: 'dining-chair',
    category: 'furniture',
    name: 'Dining Chair',
    tags: ['chair', 'seating', 'dining', 'furniture', 'modern', 'wood', 'upholstered', 'kitchen', 'seat', 'minimalist', 'timber', 'bistro'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-chair/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-chair/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/dining-chair/floor-plan.png',
    dimensions: [0.5, 1, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sprinkler',
    category: 'appliance',
    name: 'Sprinkler',
    tags: ['ceiling', 'safety'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sprinkler/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sprinkler/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sprinkler/floor-plan.png',
    dimensions: [0.5, 0.0386, 0.5],
    offset: [0, 0.0386, 0],
    rotation: [3.1416, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'exit-sign',
    category: 'appliance',
    name: 'Exit Sign',
    tags: ['sign', 'signage', 'exit', 'emergency', 'safety', 'wayfinding', 'directional', 'lighting', 'led', 'commercial', 'industrial', 'marker', 'egress', 'appliance'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/exit-sign/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/exit-sign/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/exit-sign/floor-plan.png',
    dimensions: [1, 0.5, 0.3],
    offset: [0, 0.04, 0.05],
    rotation: [0, 0, 0],
    scale: [0.6, 0.5, 0.7],
    attachTo: 'wall-side',
  },
  {
    id: 'television',
    category: 'appliance',
    name: 'Television',
    tags: ['floor', 'electronics'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/television/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/television/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/television/floor-plan.png',
    dimensions: [2, 1.1, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sewing-machine',
    category: 'appliance',
    name: 'Sewing Machine',
    tags: ['sewing', 'machine', 'appliance', 'tailor', 'craft', 'hobby', 'textile', 'metal', 'plastic', 'vintage', 'modern', 'industrial', 'mending', 'stitching'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sewing-machine/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sewing-machine/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sewing-machine/floor-plan.png',
    dimensions: [1, 0.7, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'power-outlet-moa09g0o',
    category: 'appliance',
    name: 'Power Outlet',
    tags: ['electric'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/power-outlet-moa09g0o/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/power-outlet-moa09g0o/models/item_model_PTDhACPTrrrtLLeI.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/power-outlet-moa09g0o/floor-plan.png',
    dimensions: [0.5, 0.5, 0.1],
    offset: [0, 0.26, 0.01],
    rotation: [0, 0, 0],
    scale: [0.09, 0.09, 0.09],
    attachTo: 'wall-side',
  },
  {
    id: 'iron',
    category: 'appliance',
    name: 'Iron',
    tags: ['iron', 'steamer', 'laundry', 'clothing', 'modern', 'metal', 'plastic', 'ceramic', 'garment', 'pressing', 'household', 'utility', 'appliance', 'sleek'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/iron/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/iron/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/iron/floor-plan.png',
    dimensions: [0.5, 0.3, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stereo-speaker',
    category: 'appliance',
    name: 'Stereo Speaker',
    tags: ['floor', 'electronics'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stereo-speaker/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stereo-speaker/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/stereo-speaker/floor-plan.png',
    dimensions: [0.5, 1.1, 0.5],
    offset: [0.02, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'thermostat',
    category: 'appliance',
    name: 'Thermostat',
    tags: ['wall', 'climate', 'electrical'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/thermostat/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/thermostat/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/thermostat/floor-plan.png',
    dimensions: [0.5, 0.5, 0.1],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [2.08, 2.1, 2.59],
    attachTo: 'wall-side',
  },
  {
    id: 'toaster',
    category: 'appliance',
    name: 'Toaster',
    tags: ['countertop', 'electronics'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toaster/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toaster/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toaster/floor-plan.png',
    dimensions: [0.5, 0.3, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kettle',
    category: 'appliance',
    name: 'Kettle',
    tags: ['kettle', 'teapot', 'boiler', 'electric', 'kitchen', 'appliance', 'metal', 'steel', 'modern', 'tea', 'coffee', 'boiling', 'beverage', 'breakfast'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kettle/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kettle/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kettle/floor-plan.png',
    dimensions: [0.5, 0.3, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hydrant',
    category: 'appliance',
    name: 'Hydrant',
    tags: ['hydrant', 'faucet', 'spigot', 'valve', 'metal', 'iron', 'industrial', 'vintage', 'retro', 'plumbing', 'water', 'utility', 'outdoor', 'garden', 'red'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hydrant/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hydrant/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hydrant/floor-plan.png',
    dimensions: [1, 0.9, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'computer',
    category: 'appliance',
    name: 'Computer',
    tags: ['computer', 'desktop', 'workstation', 'monitor', 'technology', 'office', 'electronics', 'modern', 'sleek', 'metal', 'silver', 'minimalist', 'hardware', 'productivity'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/computer/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/computer/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/computer/floor-plan.png',
    dimensions: [1, 0.5, 0.5],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fire-detector',
    category: 'appliance',
    name: 'Fire Detector',
    tags: ['detector', 'alarm', 'sensor', 'smoke', 'alert', 'safety', 'security', 'protection', 'appliance', 'white', 'plastic', 'minimalist', 'modern', 'warning', 'electronic'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fire-detector/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fire-detector/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fire-detector/floor-plan.png',
    dimensions: [0.5, 0.5, 0.3],
    offset: [0.02, 0.05, 0],
    rotation: [0, 0, 0],
    scale: [0.9, 1.4, 0.7],
    attachTo: 'wall',
  },
  {
    id: 'toilet-paper',
    category: 'bathroom',
    name: 'Toilet Paper',
    tags: ['wall', 'decor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet-paper/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet-paper/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet-paper/floor-plan.png',
    dimensions: [0.5, 0.5, 0.5],
    offset: [0, 0.19, 0.12],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'shower-rug',
    category: 'bathroom',
    name: 'Shower Rug',
    tags: ['rug', 'mat', 'bathmat', 'absorbent', 'cotton', 'chenille', 'modern', 'soft', 'minimalist', 'spa', 'bathroom', 'hygiene', 'plush', 'microfiber', 'woven'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-rug/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-rug/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-rug/floor-plan.png',
    dimensions: [1, 0.1, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathtub',
    category: 'bathroom',
    name: 'Bathtub',
    tags: ['bathtub', 'tub', 'bath', 'soaking', 'modern', 'minimalist', 'porcelain', 'acrylic', 'ceramic', 'bathroom', 'relaxation', 'spa'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bathtub/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bathtub/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bathtub/floor-plan.png',
    dimensions: [2.5, 0.8, 1.5],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet',
    category: 'bathroom',
    name: 'Toilet',
    tags: ['floor', 'large'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/toilet/floor-plan.png',
    dimensions: [0.5, 0.8135, 1],
    offset: [0, 0, -0.2393],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'laundry-bag',
    category: 'bathroom',
    name: 'Laundry Bag',
    tags: ['laundry', 'bag', 'hamper', 'basket', 'canvas', 'fabric', 'storage', 'organization', 'modern', 'minimalist', 'utility', 'cleaning', 'linen'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/laundry-bag/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/laundry-bag/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/laundry-bag/floor-plan.png',
    dimensions: [0.5, 0.8, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-square',
    category: 'bathroom',
    name: 'Squared Shower',
    tags: ['floor', 'large'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-square/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-square/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-square/floor-plan.png',
    dimensions: [1, 2, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathroom-sink',
    category: 'bathroom',
    name: 'Bathroom Sink',
    tags: ['sink', 'basin', 'lavatory', 'washbasin', 'vanity', 'modern', 'minimalist', 'ceramic', 'porcelain', 'white', 'plumbing', 'washing', 'bathroom', 'hygiene'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bathroom-sink/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bathroom-sink/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bathroom-sink/floor-plan.png',
    dimensions: [2, 1, 1.5],
    offset: [0.11, 0, 0.02],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-angle',
    category: 'bathroom',
    name: 'Angle Shower',
    tags: ['shower', 'enclosure', 'cubicle', 'modern', 'glass', 'corner', 'bathroom', 'chrome', 'minimalist', 'washing', 'hygiene', 'plumbing', 'stall', 'sleek'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-angle/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-angle/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/shower-angle/floor-plan.png',
    dimensions: [1, 2, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'washing-machine',
    category: 'bathroom',
    name: 'Washing Machine',
    tags: ['floor', 'large', 'electronics'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/washing-machine/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/washing-machine/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/washing-machine/floor-plan.png',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'frying-pan',
    category: 'kitchen',
    name: 'Frying Pan',
    tags: ['frying', 'pan', 'skillet', 'cookware', 'kitchen', 'cooking', 'metal', 'steel', 'nonstick', 'culinary', 'modern', 'chef', 'stove', 'utensil'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/frying-pan/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/frying-pan/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/frying-pan/floor-plan.png',
    dimensions: [0.5, 0.1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'microwave',
    category: 'kitchen',
    name: 'Microwave',
    tags: ['microwave', 'oven', 'appliance', 'kitchen', 'cooking', 'heating', 'metal', 'steel', 'modern', 'sleek', 'black', 'silver', 'electronics', 'glass', 'contemporary'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/microwave/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/microwave/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/microwave/floor-plan.png',
    dimensions: [1, 0.3, 0.5],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'cutting-board',
    category: 'kitchen',
    name: 'Cutting Board',
    tags: ['board', 'wood', 'kitchen', 'prep', 'chopping', 'serving', 'block', 'rustic', 'culinary', 'timber', 'natural', 'chef', 'cooking'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cutting-board/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cutting-board/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/cutting-board/floor-plan.png',
    dimensions: [0.5, 0.1, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hood',
    category: 'kitchen',
    name: 'Hood',
    tags: ['hood', 'vent', 'extractor', 'ventilation', 'kitchen', 'cooking', 'appliance', 'metal', 'steel', 'stainless', 'modern', 'sleek', 'industrial', 'minimalist'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hood/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hood/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/hood/floor-plan.png',
    dimensions: [1.5, 1, 1.1],
    offset: [0, 0.52, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'wooden-kitchen-bar-moa2hhh4',
    category: 'kitchen',
    name: 'Kitchen Bar',
    tags: ['bar', 'counter', 'island', 'breakfast', 'modern', 'contemporary', 'wood', 'stone', 'quartz', 'seating', 'dining', 'prep', 'entertaining'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wooden-kitchen-bar-moa2hhh4/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wooden-kitchen-bar-moa2hhh4/models/item_model_c6iR1M2eE2I8k5M3.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wooden-kitchen-bar-moa2hhh4/floor-plan.png',
    dimensions: [2.5, 1.0599, 1],
    offset: [0.0003, 0.5323, -0.0024],
    rotation: [0, 0, 0],
    scale: [2.49, 2.49, 2.49],
  },
  {
    id: 'fridge',
    category: 'kitchen',
    name: 'Fridge',
    tags: ['fridge', 'refrigerator', 'freezer', 'appliance', 'kitchen', 'storage', 'cooling', 'metal', 'steel', 'modern', 'industrial', 'minimalist', 'silver', 'sleek'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fridge/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fridge/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fridge/floor-plan.png',
    dimensions: [1, 2, 1],
    offset: [0.01, 0, -0.05],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fruits',
    category: 'kitchen',
    name: 'Fruits',
    tags: ['fruit', 'produce', 'food', 'kitchen', 'dining', 'centerpiece', 'tabletop', 'vibrant', 'fresh', 'organic', 'natural', 'accessory', 'decor', 'colorful'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fruits/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fruits/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fruits/floor-plan.png',
    dimensions: [0.5, 0.3, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen',
    category: 'kitchen',
    name: 'Kitchen',
    tags: ['kitchen', 'cabinetry', 'cabinet', 'island', 'cooking', 'storage', 'modern', 'contemporary', 'minimalist', 'wood', 'marble', 'culinary', 'pantry'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen/floor-plan.png',
    dimensions: [2.5, 1.1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    name: 'Kitchen Cabinet',
    tags: ['cabinet', 'cupboard', 'storage', 'kitchen', 'shaker', 'pantry', 'wood', 'timber', 'modern', 'contemporary', 'minimalist', 'organization'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-cabinet/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-cabinet/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-cabinet/floor-plan.png',
    dimensions: [2, 1.1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.1 },
  },
  {
    id: 'kitchen-counter',
    category: 'kitchen',
    name: 'Kitchen Counter',
    tags: ['counter', 'countertop', 'island', 'surface', 'workspace', 'stone', 'granite', 'marble', 'modern', 'kitchen', 'cooking', 'prep', 'sleek', 'polished'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-counter/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-counter/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-counter/floor-plan.png',
    dimensions: [2, 0.8, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.75 },
  },
  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    name: 'Kitchen Shelf',
    tags: ['shelf', 'shelving', 'rack', 'ledge', 'storage', 'organizer', 'kitchen', 'pantry', 'modern', 'minimalist', 'industrial', 'wood', 'metal', 'utility'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-shelf/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-shelf/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-shelf/floor-plan.png',
    dimensions: [2.5, 1, 1.1],
    offset: [0, 0.52, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'wine-bottle',
    category: 'kitchen',
    name: 'Wine Bottle',
    tags: ['countertop', 'decor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wine-bottle/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wine-bottle/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/wine-bottle/floor-plan.png',
    dimensions: [0.5, 0.4, 0.5],
    offset: [-0.05, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    name: 'Kitchen Utensils',
    tags: ['utensils', 'tools', 'kitchenware', 'cooking', 'prep', 'steel', 'silicone', 'wood', 'modern', 'gadgets', 'accessories', 'silverware', 'chef', 'serving', 'baking'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-utensils/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-utensils/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/kitchen-utensils/floor-plan.png',
    dimensions: [0.5, 0.5, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fir-tree',
    category: 'outdoor',
    name: 'Fir',
    tags: ['fir', 'tree', 'plant', 'evergreen', 'conifer', 'foliage', 'greenery', 'natural', 'garden', 'outdoor', 'botanical', 'rustic', 'alpine', 'woodland'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fir-tree/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fir-tree/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/fir-tree/floor-plan.png',
    dimensions: [0.5, 3, 0.5],
    offset: [-0.01, 0.05, -0.07],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ball',
    category: 'outdoor',
    name: 'Ball',
    tags: ['ball', 'sphere', 'orb', 'globe', 'round', 'modern', 'minimalist', 'decor', 'garden', 'patio', 'sculpture', 'ornament', 'accent', 'circular', 'contemporary'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ball/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ball/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/ball/floor-plan.png',
    dimensions: [0.5, 0.2388, 0.5],
    offset: [-0.0001, 0.1194, -0.0001],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bush',
    category: 'outdoor',
    name: 'Bush',
    tags: ['bush', 'shrub', 'plant', 'greenery', 'foliage', 'hedge', 'natural', 'organic', 'lush', 'landscaping', 'garden', 'yard', 'botanical', 'outdoor', 'decorative'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bush/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bush/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/bush/floor-plan.png',
    dimensions: [3, 1.1, 1],
    offset: [-0.14, 0.01, -0.13],
    rotation: [0, 0, 0],
    scale: [0.96, 0.96, 0.96],
  },
  {
    id: 'basket-hoop',
    category: 'outdoor',
    name: 'Basket Hoop',
    tags: ['hoop', 'basketball', 'rim', 'net', 'goal', 'sporty', 'recreation', 'outdoor', 'metal', 'steel', 'athletic', 'game', 'play', 'leisure', 'activity'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/basket-hoop/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/basket-hoop/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/basket-hoop/floor-plan.png',
    dimensions: [1, 1.7727, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'parking-spot',
    category: 'outdoor',
    name: 'Parking Spot',
    tags: ['parking', 'space', 'stall', 'driveway', 'pavement', 'asphalt', 'concrete', 'urban', 'industrial', 'utility', 'vehicle', 'outdoor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/parking-spot/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/parking-spot/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/parking-spot/floor-plan.png',
    dimensions: [5, 1, 2.5],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [0.9, 1, 0.78],
  },
  {
    id: 'tesla',
    category: 'outdoor',
    name: 'Tesla Model Y',
    tags: ['tesla', 'car', 'vehicle', 'automobile', 'electric', 'modern', 'minimalist', 'sleek', 'metal', 'glass', 'luxury', 'transportation', 'commuting'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tesla/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tesla/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tesla/floor-plan.png',
    dimensions: [2, 1.7, 5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'palm',
    category: 'outdoor',
    name: 'Palm',
    tags: ['palm', 'tree', 'plant', 'tropical', 'exotic', 'foliage', 'greenery', 'botanical', 'garden', 'patio', 'outdoor', 'lush', 'organic', 'nature'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/palm/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/palm/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/palm/floor-plan.png',
    dimensions: [1, 4.5, 1],
    offset: [0, 0, 0.02],
    rotation: [0, 0, 0],
    scale: [0.37, 0.37, 0.37],
  },
  {
    id: '1967-chevrolet-camaro-moa24wsf',
    category: 'outdoor',
    name: '1967 Chevrolet Camaro',
    tags: ['car'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/1967-chevrolet-camaro-moa24wsf/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/1967-chevrolet-camaro-moa24wsf/models/item_model_vUIp1N69V9RXLqoJ.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/1967-chevrolet-camaro-moa24wsf/floor-plan.png',
    dimensions: [4.5, 1.2166, 2],
    offset: [-0.0024, 0.5993, 0.0209],
    rotation: [0, 0, 0],
    scale: [4.09, 4.09, 4.09],
  },
  {
    id: 'scooter',
    category: 'outdoor',
    name: 'Scooter',
    tags: ['scooter', 'kickscooter', 'transport', 'mobility', 'outdoor', 'wheels', 'metal', 'aluminum', 'modern', 'sleek', 'urban', 'active', 'travel', 'ride', 'commute'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/scooter/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/scooter/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/scooter/floor-plan.png',
    dimensions: [1, 0.9, 0.5],
    offset: [0.11, 0, 0.17],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sunbed',
    category: 'outdoor',
    name: 'Sunbed',
    tags: ['leisure', 'seating', 'floor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sunbed/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sunbed/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/sunbed/floor-plan.png',
    dimensions: [1, 1.2, 1.5],
    offset: [0, 0.04, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tree',
    category: 'outdoor',
    name: 'Tree',
    tags: ['vegetation'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tree/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tree/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/tree/floor-plan.png',
    dimensions: [1, 5, 1],
    offset: [-0.02, 0.17, -0.04],
    rotation: [0, 0, 0],
    scale: [0.65, 0.65, 0.65],
  },
  {
    id: 'pillar',
    category: 'outdoor',
    name: 'Pillar',
    tags: ['pillar', 'column', 'pedestal', 'plinth', 'stone', 'concrete', 'classical', 'architectural', 'garden', 'ornament', 'decoration', 'support'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pillar/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pillar/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/pillar/floor-plan.png',
    dimensions: [0.5, 1.3, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'skate',
    category: 'outdoor',
    name: 'Skate',
    tags: ['leisure', 'kids', 'floor'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/skate/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/skate/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/skate/floor-plan.png',
    dimensions: [1, 0.2, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    name: 'Outdoor Playhouse',
    tags: ['playhouse', 'cottage', 'cabin', 'fort', 'wood', 'cedar', 'garden', 'backyard', 'kids', 'children', 'play', 'recreation', 'outdoor', 'rustic', 'timber'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/outdoor-playhouse/thumbnail.png',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/outdoor-playhouse/model.glb',
    floorPlanUrl: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/outdoor-playhouse/floor-plan.png',
    dimensions: [0.5, 0.5, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'door',
    category: 'door',
    name: 'Door',
    tags: ['door', 'entry', 'entrance', 'portal', 'modern', 'minimalist', 'industrial', 'wood', 'metal', 'glass', 'interior', 'passage', 'privacy', 'swing', 'timber'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/door/thumbnail.webp',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/door/model.glb',
    dimensions: [1.5, 2, 0.4],
    offset: [-0.43, 0, 0],
    rotation: [0, 0, 0],
    scale: [0.79, 0.79, 0.79],
    attachTo: 'wall',
  },
  {
    id: 'glass-door',
    category: 'door',
    name: 'Glass Door',
    tags: ['door', 'glass', 'entryway', 'transparent', 'modern', 'minimalist', 'contemporary', 'partition', 'entrance', 'sleek', 'clear', 'architectural'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/glass-door/thumbnail.webp',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/glass-door/model.glb',
    dimensions: [1.5, 2.5, 0.4],
    offset: [-0.52, 0, 0],
    rotation: [0, 0, 0],
    scale: [0.9, 0.9, 0.9],
    attachTo: 'wall',
  },
  {
    id: 'door-bar',
    category: 'door',
    name: 'Door with bar',
    tags: ['door', 'entryway', 'industrial', 'rustic', 'farmhouse', 'wood', 'timber', 'metal', 'sliding', 'hardware', 'passage', 'handle', 'modern', 'contemporary'],
    thumbnail: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/door-bar/thumbnail.webp',
    src: 'https://byrpxoiotywskoojsrzd.supabase.co/storage/v1/object/public/items/system/door-bar/model.glb',
    dimensions: [1.5, 2.5, 0.5],
    offset: [-0.48, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
]

export function getDefaultCatalogItem(category: string | null | undefined): AssetInput | null {
  if (!category) return null
  return CATALOG_ITEMS.find((item) => item.category === category) ?? null
}
